---
# tasks file for mysql-replication-slave
- name: Install required packages
  apt:
    pkg="{{ item }}"
    state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Set slave server ID
  lineinfile:
    dest=/etc/mysql/my.cnf
    insertafter="\[mysqld\]"
    line="{{ item }}"
    state=present
  with_items:
    - "relay-log=mysqld-relay-bin"
    - "report-host={{ ansible_hostname }}"
    - "server-id={{ ansible_ssh_host_key_rsa_public.count('J') + ansible_ssh_host_key_rsa_public.count('j') + 2 }}"

- name: Leave MySQL server stopped
  service:
    name=mysql
    state=stopped
